import Link from "next/link";
import { eur, loadEpisodes, paymentMethodLabel } from "@/lib/dashboard";
import { loadPrivateContacts } from "@/lib/admin";

export default async function Sales(){
  const [rows,privateData]=await Promise.all([loadEpisodes(),loadPrivateContacts()]);
  const phones=new Map((privateData.contacts||[]).map((c:any)=>[c.customer_id,c.phone_e164||c.whatsapp_number]));
  return <div>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-violet-300">Sales</p><h1 className="mt-1 text-3xl font-semibold">Épisodes de vente</h1></div>{!privateData.unlocked&&<Link href="/admin" className="rounded-xl border border-amber-400/15 bg-amber-400/10 px-3 py-2 text-xs text-amber-200">Déverrouiller les téléphones</Link>}</div>
    <div className="panel overflow-x-auto rounded-2xl"><table className="w-full min-w-[1040px] text-left text-sm"><thead className="border-b border-white/8 text-xs text-white/35"><tr>{["Client","Date","Produits","Total","Moyen de paiement","Paiement","Confiance","Statut"].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{(rows as any[]).map(r=>{const phone=phones.get(r.customer_id);return <tr key={r.id} className="border-b border-white/5 hover:bg-white/[.025]"><td className="px-4 py-3"><Link className="font-medium hover:text-violet-300" href={`/sales/${r.id}`}>{r.customers?.display_name||"Client"}</Link>{privateData.unlocked&&phone&&<div className="mt-1 text-xs text-emerald-300/70">{phone}</div>}</td><td className="px-4 py-3 text-white/50">{r.ordered_at?new Date(r.ordered_at).toLocaleDateString("fr-BE"):"—"}</td><td className="px-4 py-3 text-white/65">{r.order_items?.map((i:any)=>`${i.quantity||"?"}× ${i.product_name}`).join(", ")||"—"}</td><td className="px-4 py-3">{r.total==null?"À valider":eur(Number(r.total))}</td><td className="px-4 py-3"><span className="rounded-full bg-white/5 px-2 py-1 text-xs text-white/65">{paymentMethodLabel(r.payment_method)}</span></td><td className="px-4 py-3 text-white/55">{r.payment_status}</td><td className="px-4 py-3">{Math.round(Number(r.confidence)*100)}%</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs ${r.classification==="confirmed"&&r.revenue_eligible?"bg-emerald-500/10 text-emerald-300":r.classification==="probable"?"bg-amber-500/10 text-amber-200":"bg-white/5 text-white/50"}`}>{r.classification}</span></td></tr>})}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-white/35">Aucun épisode importé dans la base dédiée.</p>}</div>
  </div>;
}
